### ISSUE TITLE
Check-in page

### ISSUE THREAD

**Issue by 30ann** [IDEMSInternational/plh-kids-app-content#3]
As a user:
- A consistent identifiable place on a page when the app provides a user with feedback ‘or talks to me’ would be helpful.

Navigations:
- To the page: After a user selects the X on the Relax page.
- To exit page: X at the top.
- The next button which appears after the user selects an emoji takes you to the next page.

Key Features:

- The icon at the top of the check-in is the same as that used in the chapter menu.

- Include a caption of the emojis.
- The selection of an icon greys out the emoji.
- A grey box at the bottom of the page with an avatar provides feedback once an emoji is selected.
- The avatar might change depending on the gender of the user/selected avatar.

<img width="284" alt="image4" src="https://github.com/IDEMSInternational/plh-kids-app-content/assets/112470669/2280b1a4-3096-4e97-b3f6-311ffb0124c5">

**Comment by esmeetewinkel** [comment]
Discussion Maryann / Esmee: 
- this will be an article page

Action points: 
- [ ] grey display group style: https://github.com/IDEMSInternational/parenting-app-ui/issues/2149
- [ ] display group option to have "image touch the border" https://github.com/IDEMSInternational/parenting-app-ui/issues/2151
- [ ] app without header: https://github.com/IDEMSInternational/parenting-app-ui/issues/2154
- [ ] category navigation: https://github.com/IDEMSInternational/parenting-app-ui/issues/2150
    - progress bar when a category has multiple articles (when only one article it doesn't appear)
    - "cross" takes you back to module overview
    - "next" takes you to next article within category. If you're at the last article of the category, this will take you to the first article of the following category
